package de.tsystems.onsite.bookabooth.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CompanyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyAllPropertiesEquals(Company expected, Company actual) {
        assertCompanyAutoGeneratedPropertiesEquals(expected, actual);
        assertCompanyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyAllUpdatablePropertiesEquals(Company expected, Company actual) {
        assertCompanyUpdatableFieldsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyAutoGeneratedPropertiesEquals(Company expected, Company actual) {
        assertThat(expected)
            .as("Verify Company auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompanyUpdatableFieldsEquals(Company expected, Company actual) {
        assertThat(expected)
            .as("Verify Company relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getBillingAddressRow1()).as("check billingAddressRow1").isEqualTo(actual.getBillingAddressRow1()))
            .satisfies(e -> assertThat(e.getBillingAddressRow2()).as("check billingAddressRow2").isEqualTo(actual.getBillingAddressRow2()))
            .satisfies(e -> assertThat(e.getBillingAddressRow3()).as("check billingAddressRow3").isEqualTo(actual.getBillingAddressRow3()))
            .satisfies(e -> assertThat(e.getBillingAddressRow4()).as("check billingAddressRow4").isEqualTo(actual.getBillingAddressRow4()))
            .satisfies(e -> assertThat(e.getBillingZipCode()).as("check billingZipCode").isEqualTo(actual.getBillingZipCode()))
            .satisfies(e -> assertThat(e.getBillingCity()).as("check billingCity").isEqualTo(actual.getBillingCity()))
            .satisfies(e -> assertThat(e.getComment()).as("check comment").isEqualTo(actual.getComment()))
            .satisfies(e -> assertThat(e.getLogo()).as("check logo").isEqualTo(actual.getLogo()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getWaitingList()).as("check waitingList").isEqualTo(actual.getWaitingList()))
            .satisfies(e -> assertThat(e.getExhibitorList()).as("check exhibitorList").isEqualTo(actual.getExhibitorList()));
    }
}
