package de.tsystems.onsite.bookabooth.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SystemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemAllPropertiesEquals(System expected, System actual) {
        assertSystemAutoGeneratedPropertiesEquals(expected, actual);
        assertSystemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemAllUpdatablePropertiesEquals(System expected, System actual) {
        assertSystemUpdatableFieldsEquals(expected, actual);
        assertSystemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemAutoGeneratedPropertiesEquals(System expected, System actual) {
        assertThat(expected)
            .as("Verify System auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemUpdatableFieldsEquals(System expected, System actual) {
        assertThat(expected)
            .as("Verify System relevant properties")
            .satisfies(e -> assertThat(e.getEnabled()).as("check enabled").isEqualTo(actual.getEnabled()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSystemUpdatableRelationshipsEquals(System expected, System actual) {}
}
